name: Luqven
favicon: null
layout_spectrum: 0.74833
typography_spectrum: 0.84197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0500f2'
    - '#df0005'
    - '#e1dad0'
    - '#e100e0'
  brandStrength: 0.5
  lightness: 0.49045521626248956
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
